source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CalendarView_Example' do
  pod 'WTCalendarView', :path => '../'
  target 'CalendarView_Tests' do
    inherit! :search_paths
  end
end

