source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CalendarView_Example', :exclusive => true do
  pod 'CalendarView', :path => '../'
end

target 'CalendarView_Tests', :exclusive => true do
  pod 'CalendarView', :path => '../'

  
end
